[package]
name = "z80"
version = "0.1.0"
authors = ["Ivan Izaguirre <ivanizag@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "cpm"
path = "src/cpm/cpm.rs"

[dependencies]
clap = "^2"
