[package]
name = "rcpm"
version = "0.1.0"
authors = ["Ivan Izaguirre <ivanizag@gmail.com>"]
edition = "2018"

[[bin]]
name = "rcpm"
path = "src/main.rs"

[dependencies]
z80 = { path = "../rust-z80" }
clap = "^2"
