[package]
name = "rcpm"
version = "0.1.0"
authors = ["Ivan Izaguirre <ivanizag@gmail.com>"]
edition = "2018"

[[bin]]
name = "iz-cpm"
path = "src/main.rs"

[dependencies]
iz80 = { path = "../iz80" }
clap = "^2"
